//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticAnalysisGUI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StaticAnalyserToolControllerAbsolute", ReplyAction="http://tempuri.org/IService1/StaticAnalyserToolControllerAbsoluteResponse")]
        string StaticAnalyserToolControllerAbsolute(string userName, string repositoryName, string acceptanceLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StaticAnalyserToolControllerAbsolute", ReplyAction="http://tempuri.org/IService1/StaticAnalyserToolControllerAbsoluteResponse")]
        System.Threading.Tasks.Task<string> StaticAnalyserToolControllerAbsoluteAsync(string userName, string repositoryName, string acceptanceLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StaticAnalyserToolControllerRelative", ReplyAction="http://tempuri.org/IService1/StaticAnalyserToolControllerRelativeResponse")]
        string StaticAnalyserToolControllerRelative(string userName, string repositoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StaticAnalyserToolControllerRelative", ReplyAction="http://tempuri.org/IService1/StaticAnalyserToolControllerRelativeResponse")]
        System.Threading.Tasks.Task<string> StaticAnalyserToolControllerRelativeAsync(string userName, string repositoryName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : StaticAnalysisGUI.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<StaticAnalysisGUI.ServiceReference1.IService1>, StaticAnalysisGUI.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string StaticAnalyserToolControllerAbsolute(string userName, string repositoryName, string acceptanceLevel) {
            return base.Channel.StaticAnalyserToolControllerAbsolute(userName, repositoryName, acceptanceLevel);
        }
        
        public System.Threading.Tasks.Task<string> StaticAnalyserToolControllerAbsoluteAsync(string userName, string repositoryName, string acceptanceLevel) {
            return base.Channel.StaticAnalyserToolControllerAbsoluteAsync(userName, repositoryName, acceptanceLevel);
        }
        
        public string StaticAnalyserToolControllerRelative(string userName, string repositoryName) {
            return base.Channel.StaticAnalyserToolControllerRelative(userName, repositoryName);
        }
        
        public System.Threading.Tasks.Task<string> StaticAnalyserToolControllerRelativeAsync(string userName, string repositoryName) {
            return base.Channel.StaticAnalyserToolControllerRelativeAsync(userName, repositoryName);
        }
    }
}
